// Generated by typings
// Source: https://raw.githubusercontent.com/gaearon/redux-thunk/22946983b612e726156ac9059c56bb8d36c93bca/index.d.ts
declare module 'redux-thunk' {
import {Middleware, Dispatch} from 'redux';


export type ThunkAction<R, S, E> = (dispatch: Dispatch<S>, getState: () => S,
                                    extraArgument: E) => R;

module 'redux' {
  export interface Dispatch<S> {
    <R, E>(asyncAction: ThunkAction<R, S, E>): R;
  }
}


const thunk: Middleware & {
  withExtraArgument(extraArgument: any): Middleware;
};

export default thunk;
}
